extracao/urls.py
from django.conf.urls import url  
from django.contrib import admin

from . import views


app_name = 'extracao'

urlpatterns = [
    url(r'^admin/', admin.site.urls),           
    
    url(r'^$', views.index, name='index'),
    
    url(r'^register/$', views.register, name='register'),
    
    url(r'^login_user/$', views.login_user, name='login_user'),
    
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    
    url(r'^(?P<workspace_id>[0-9]+)/$', views.detail, name='detail'),
    
    url(r'^(?P<workspace_id>[0-9]+)/process/$', views.detail_process, name='detail_process'),
      
    url(r'^select_social/$', views.select_social, name='select_social'),
    
    url(r'^add_workspace_facebook/$', views.create_workspace_facebook, name='create_workspace_facebook'),
    
    url(r'^add_workspace_twitter/$', views.create_workspace_twitter, name='create_workspace_twitter'),
    
    url(r'^(?P<workspace_id>[0-9]+)/create_facebook_post/$', views.create_facebook_post, name='create_facebook_post'),
    
    url(r'^(?P<workspace_id>[0-9]+)/create_twitter_post/$', views.create_twitter_post, name='create_twitter_post'),
    
    url(r'^(?P<workspace_id>[0-9]+)/processing_twitter_post/$', views.processing_twitter_post, name='processing_twitter_post'),
    
    url(r'^(?P<workspace_id>[0-9]+)/processing_facebook_post/$', views.processing_facebook_post, name='processing_facebook_post'),
    
    url(r'^(?P<workspace_id>[0-9]+)/delete_post_fanpage/(?P<post_id>[0-9]+)/$', views.delete_post_fanpage, name='delete_post_fanpage'),
    
    url(r'^(?P<workspace_id>[0-9]+)/delete_post_tagged/(?P<tagged_id>[0-9]+)/$', views.delete_post_fanpage, name='delete_post_tagged'),
    
    url(r'^(?P<workspace_id>[0-9]+)/delete_post_tweet/(?P<tweet_id>[0-9]+)/$', views.delete_post_tweet, name='delete_post_tweet'),
         
    url(r'^(?P<workspace_id>[0-9]+)/delete_workspace/$', views.delete_workspace, name='delete_workspace'),
    
    url(r'^(?P<workspace_id>[0-9]+)/update_workspace_facebook/$', views.update_workspace_facebook, name='update_workspace_facebook'),
    
    url(r'^(?P<workspace_id>[0-9]+)/update_workspace_twitter/$', views.update_workspace_twitter, name='update_workspace_twitter'),
      
    url(r'^(?P<tipo>.+)export_process_post/$', views.export_process_post, name='export_process_post'),
    
    url(r'^(?P<tipo>.+)export_process_tweet/$', views.export_process_tweet, name='export_process_tweet'),
    
    url(r'^(?P<workspace_id>[0-9]+)/testejs/$', views.testejs, name='testejs'),   
    
]

scrm/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin 

from extracao import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='scrm_index'),
    url(r'^extracao/', include("extracao.urls")),
    url(r'^email/$', views.email, name='email'),
    url(r'^thanks/$', views.thanks, name='thanks'),
    url(r'^', include("extracao.urls")),  
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.ARQUIVOS_URL, document_root=settings.ARQUIVOS_ROOT)

extracao/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import Permission, User
from django.core.urlresolvers import reverse
from django.db import models


class Workspace(models.Model):
    face_choice = (
        (u'Facebook: fanpage', u'fanpage'),
        (u'Facebook: tagged', u'tagged'),
    )
    
    tweet_choice = (
        (u'twitter', u'twitter'),
    )
    user = models.ForeignKey(User, default=1)
    extracao_facebook = models.CharField(max_length=50, choices=face_choice)
    user_token = models.CharField(max_length=100)
    extracao_twitter = models.CharField(max_length=50, choices=tweet_choice)
    ckey = models.CharField(max_length=50)
    csecret = models.CharField(max_length=50)
    atoken = models.CharField(max_length=50)
    asecret = models.CharField(max_length=50)
    #is_favorite = models.BooleanField(default=False)
        
    def __str__(self):
        return self.extracao_facebook + self.extracao_twitter + ' | ' + str(self.user)

class Fanpage(models.Model):
    workspace = models.ForeignKey(Workspace, on_delete=models.CASCADE)
    page_id = models.CharField(max_length=30, null=True)
    page = models.CharField(max_length=100)
    page_name =  models.CharField(max_length=100, null=True)
    
    def __str__(self):
        return self.page

class Post(models.Model):
    post_choice = (
        (u'Post: atualizar_base', u'Atualizar Base'),
        (u'Post: extracao_completa', u'Extração Completa'),
    )
    
    workspace = models.ForeignKey(Workspace, on_delete=models.CASCADE)
    page = models.ForeignKey(Fanpage, on_delete=models.CASCADE)
    tipo_extracao = models.CharField(max_length=50, choices=post_choice)
    post_id = models.CharField(max_length=50)
    created_time =  models.DateTimeField()
    message =  models.TextField()
    shares = models.IntegerField()
    likes = models.IntegerField()
    reactions = models.IntegerField()
    comment = models.IntegerField()
    post_type =  models.CharField(max_length=10)
    media_type =  models.TextField()
    
    def __str__(self):
        return str(self.page)
    
    def get_absolute_url(self):
        return reverse("extracao:detail_face", kwargs={"workspace_id": self.workspace})

class Post_comment(models.Model):
    workspace = models.ForeignKey(Workspace, on_delete=models.CASCADE)    
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_id = models.CharField(max_length=50)
    created_time =  models.DateTimeField()
    message =  models.TextField()
    from_id =  models.CharField(max_length=30)
    from_name =  models.CharField(max_length=255)
    comment_count = models.IntegerField()
    like_count = models.IntegerField()
    
    def __str__(self):
        return str(self.post)
    
class Post_like(models.Model):    
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    id_user = models.CharField(max_length=50)
    name_user =  models.CharField(max_length=255)
    imagem_profile = models.TextField()
    
    def __str__(self):
        return str(self.post)    
    
class Post_reaction(models.Model):    
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    id_user = models.CharField(max_length=50)
    name_user =  models.CharField(max_length=255)
    reaction_type = models.CharField(max_length=20)
    
    def __str__(self):
        return str(self.post) 
    
class Processamento_post(models.Model):    
    workspace = models.ForeignKey(Workspace, on_delete=models.CASCADE)
    page = models.ForeignKey(Fanpage, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    message_origin =  models.TextField()
    message_tratament =  models.TextField(null=True)
    message_demojize =  models.TextField(null=True)
    message =  models.TextField(null=True)
    
    def __str__(self):
        return str(self.post) 
    
class Processamento_comment(models.Model):    
    workspace = models.ForeignKey(Workspace, on_delete=models.CASCADE)
    page = models.ForeignKey(Fanpage, on_delete=models.CASCADE)
    comment = models.ForeignKey(Post, on_delete=models.CASCADE)
    message_origin =  models.TextField()
    message_tratament =  models.TextField(null=True)
    message_demojize =  models.TextField(null=True)
    message =  models.TextField(null=True)
    
    def __str__(self):
        return str(self.post)                    

class Tagged(models.Model):
    post_choice = (
        (u'Post: Atualizar Base', u'atualizar base'),
        (u'Post: Extração Completa', u'extração completa'),
    )
    
    workspace = models.ForeignKey(Workspace, on_delete=models.CASCADE)
    page = models.ForeignKey(Fanpage, on_delete=models.CASCADE)
    tipo_extracao = models.CharField(max_length=50, choices=post_choice)
    post_id = models.CharField(max_length=50)
    created_time =  models.DateTimeField()
    message =  models.TextField()
    shares = models.IntegerField()
    likes = models.IntegerField()
    reactions = models.IntegerField()
    comment = models.IntegerField()
    post_type =  models.CharField(max_length=10)
    media_type =  models.TextField()
    
    def __str__(self):
        return str(self.page)

# MODELS DO TWITTER

class Tweet(models.Model):
    workspace = models.ForeignKey(Workspace, on_delete=models.CASCADE)
    termo_consulta = models.CharField(max_length=50)
    criacao = models.CharField(max_length=19, null=True)
    tweet_id = models.CharField(max_length=20, null=True)
    tweet = models.TextField(null=True)
    usuario = models.CharField(max_length=20, null=True)
    lingua = models.CharField(max_length=10, null=True)
    seguidores = models.CharField(max_length=10, null=True)
    amigos = models.CharField(max_length=10, null=True)
    localidade = models.CharField(max_length=50, null=True)
    #is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.termo_consulta
    
class Processamento_tweet(models.Model): 
    workspace = models.ForeignKey(Workspace, on_delete=models.CASCADE)   
    tweet = models.ForeignKey(Tweet, on_delete=models.CASCADE)
    tweet_origin =  models.TextField()
    tweet_tratament =  models.TextField(null=True)
    tweet_demojize =  models.TextField(null=True)
    tweet_process =  models.TextField(null=True)
    
    def __str__(self):
        return str(self.post) 

# FIM MODELS TWITTER

class Contact(models.Model):
    name = models.CharField(max_length=100, null=False)
    email = models.EmailField(max_length=100, null=False)
    message = models.TextField(max_length=100, null=False)
    phone = models.CharField(max_length=11, null=False)

extracao/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Workspace, Fanpage, Post, Tagged, Tweet, Contact


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class WorkspaceFacebookForm(forms.ModelForm):

    class Meta:
        model = Workspace
        fields = ['extracao_facebook', 'user_token']

class WorkspaceTwitterForm(forms.ModelForm):

    class Meta:
        model = Workspace
        fields = ['extracao_twitter', 'ckey', 'csecret', 'atoken', 'asecret']


class FacebookFanpageForm(forms.ModelForm):

    class Meta:
        model = Fanpage
        fields = ['page']

class FacebookPostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['tipo_extracao']

class FacebookTaggedForm(forms.ModelForm):

    class Meta:
        model = Tagged
        fields = ['page', 'tipo_extracao']

# Forms para tweeter

class TwitterPostForm(forms.ModelForm):
    class Meta:
        model = Tweet
        fields = ['termo_consulta']
        
# Fim Forms para tweeter


class ContactForm(forms.ModelForm):
    
    class Meta:
        model = Contact
        fields = ['name', 'email', 'message', 'phone']

extracao/templates/extracao/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
{% load static %}    
    <meta charset="UTF-8">
    <title>{% block title %}SocialCRM{% endblock %}</title>
    {% load staticfiles %}
    <link href="{% static "startbootstrap_agency/vendor/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <!-- Bootstrap Core CSS -->
    <link href="{% static "startbootstrap_agency/vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'extracao/style.css' %}"/>
    
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>  -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
     
           <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
     
     
    <!--  Montagem de tabelas --> 
    
    <script src="{% static 'extracao/js/jquery-1.12.3.js' %}"></script> 
	<script src="{% static 'extracao/js/jquery.dataTables.min.js' %}"></script>
	<script src="{% static 'extracao/js/dataTables.bootstrap.min.js' %}"></script>
	<script src="{% static 'extracao/js/table.js' %}"></script> 
	 
    <script src="{% static 'extracao/js/main.js' %}"></script>    
    
</head>

<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'extracao:index' %}">SocialCRM</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block workspaces_active %}{% endblock %}"><a href="{% url 'extracao:index' %}"><span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>&nbsp; Workspaces</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'extracao:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Pesquisa</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'extracao:select_social' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Workspace
                    </a>
                </li>
                <li>
                    <a href="{% url 'extracao:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}

</body>
</html>

extracao/templates/extracao/detail.html
{% extends 'extracao/base.html' %}
{% block title %}Detalhes Extração{% endblock %}
{% block workspaces_active %}active{% endblock %}

{% block body %}
{% load static%}
<meta charset="UTF-8">

<div class="container-fluid">

    <div class="row">

        <!-- Left Workspace Info -->
        <div class="col-sm-4 col-md-12">
            <div class="panel panel-default">
                <a href="{% url 'extracao:detail' workspace.id %}"></a>
		             {% if workspace.extracao_twitter %}
		             <img src="{% static "extracao/images/twitter.jpg" %}" class="img-responsive"> 
		             <strong>{{ workspace.extracao_twitter }}</strong><br> 
		             <strong>Consulta:</strong><small> {{ workspace.termo_consulta }}</small><br>
                     
                     <strong>ckey:</strong><small> {{ workspace.ckey }}</small><br>
                     <strong>asecret:</strong><small> {{ workspace.asecret }}</small><br>
                     <strong>csecret:</strong><small> {{ workspace.csecret }}</small><br>
                     <strong>atoken:</strong><small> {{ workspace.atoken }}</small>
                    {% else %}
		                <div class="panel-body">
		                <img src="{% static "extracao/images/face.jpg" %}" class="img-responsive">
		                    <h4>{{ workspace.extracao_facebook }}</h4>
		                    <h4><small><strong>User Token:</strong> {{ workspace.user_token }}</small></h4>
		                </div>
                	{% endif %}
            </div>
        </div>
    </div>
    <div class="row">
        {% if workspace.extracao_twitter %}
        
        <div class="col-sm-4 col-md-4">
	         <ul class="nav nav-pills" style="margin: 2px 2px;">
	            <li role="presentation" class="active"><a href="{% url 'extracao:detail' workspace.id %}">Vizualizar</a></li>
	            <li role="presentation"><a href="{% url 'extracao:create_twitter_post' workspace.id %}">Extrair</a></li>
	            <li role="presentation"><a href="{% url 'extracao:processing_twitter_post' workspace.id %}">Pré-Processamento</a></li>
	         </ul>
        </div>
        {% else %}
        <div class="col-sm-4 col-md-4">
	         <ul class="nav nav-pills" style="margin: 2px 2px;">
	            <li role="presentation" class="active"><a href="{% url 'extracao:detail' workspace.id %}">Vizualizar</a></li>
	            <li role="presentation"><a href="{% url 'extracao:create_facebook_post' workspace.id %}">Extrair</a></li>
	            <li role="presentation"><a href="{% url 'extracao:processing_facebook_post' workspace.id %}">Pré-Processamento</a></li>
	         </ul>
        </div>
		{% endif %}
   </div>
   <div class="row">	
        <!-- Right post Info -->
        <div class="col-sm-4 col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    
                    {% if workspace.extracao_twitter %}
                    	<table id="exemplo" class="table table-striped table-bordered" cellspacing="0" width="100%">
				          	<thead>
				          		<tr>
				              		<th>Mensagem</th>
				             		<th>Ação</th> 
				          	    </tr>
				            </thead>
				            <tfoot>
				            	<tr>
				                	<th>Mensagem</th>
 				                	<th>Ação</th> 
				           	   </tr>
				            </tfoot>
				            
				            <tbody>
				        	{% for tweet in workspace.tweet_set.all %}
	                           <tr>                      
	                              <!-- nome coluna: Mensagem -->
	                              <td>
	                                 {{tweet.tweet}}
	                              </td>
							      <!-- nome coluna: Ação -->
	                              <td>
	                                  <form action="{% url 'extracao:delete_post_tweet' workspace.id tweet.id %}" method="post" style="display: inline;">
	                                       {% csrf_token %}
	                                       <input type="hidden" name="tweet_id" value="{{ tweet.id }}" />
	                                       		<button type="submit" class="btn btn-danger btn-xs">
	                                            <span class="glyphicon glyphicon-remove"></span>&nbsp;
	                                       </button>
	                                  </form>
	                              </td>
	                            </tr>
	                        {% endfor %}
	                       </tbody>
	                    </table>
	                {% else %}
                       	<table id="exemplo" class="table table-striped table-bordered" cellspacing="0" width="100%">  
                       	    <thead>
			            		<tr>
			                		<th>Mensagem</th>
				                		<th>Created_time</th> 
 				                	<th>Likes</th>
					                	<th>Shares</th> 
					                	<th>Reactions</th>
					                	<th>Comments</th> 
			            		    <th>Ação</th>
			            		</tr>
			        		</thead>
			        		<tfoot>
			            		<tr>
			                		<th>Mensagem</th>
				                		<th>Created_time</th> 
 				                	<th>Likes</th>
					                	<th>Shares</th> 
					                	<th>Reactions</th>
					                	<th>Comments</th> 
			            		    <th>Ação</th>
			            		</tr>
			        		</tfoot>
			        		<tbody>
			        		{% for post in workspace.post_set.all %}
	                            <tr>
	                                <!-- nome coluna: Mensagem -->
	                                <td>
	                                    {{post.message}}
	                                </td>
	                                <td>
	                                    {{post.created_time}}
	                                </td>
									<td>
	                                    {{post.likes}}
	                                </td>
	                                <td>
	                                    {{post.shares}}
	                                </td>
	                                <td>
	                                    {{post.reactions}}
	                                </td>
	                                <td>
	                                    {{post.comment}}
	                                </td>
                                <!-- nome coluna: Ação -->
	                                <td>
	                                    <form action="{% url 'extracao:delete_post_fanpage' workspace.id post.id %}" method="post" style="display: inline;">
	                                        {% csrf_token %}
	                                        <input type="hidden" name="post_id" value="{{ post.id }}" />
	                                        <button type="submit" class="btn btn-danger btn-xs">
	                                            <span class="glyphicon glyphicon-remove"></span>&nbsp;
	                                        </button>
	                                    </form>
	                                </td>
                           		  {% endfor %}
                           		 </tr>
                            </tbody>
                        </table>
	                {% endif %}
				</div>
            </div>
        </div>
    </div>
</div>

{% endblock %}   

extracao/templates/extracao/detail_process.html
{% extends 'extracao/base.html' %}
{% block title %}Detalhes Processamento{% endblock %}
{% block workspaces_active %}active{% endblock %}

{% block body %}

{% load static%}
<meta charset="UTF-8">

<div class="container-fluid">

    <div class="row">

        <!-- Left Workspace Info -->
        <div class="col-sm-4 col-md-12">
            <div class="panel panel-default">
                <a href="{% url 'extracao:detail_process' workspace.id %}"></a>
		             {% if workspace.extracao_twitter %}
		             <img src="{% static "extracao/images/twitter.jpg" %}" class="img-responsive"> 
		             <strong>{{ workspace.extracao_twitter }}</strong><br> 
		             <strong>Consulta:</strong><small> {{ workspace.termo_consulta }}</small><br>
                     
                     <strong>ckey:</strong><small> {{ workspace.ckey }}</small><br>
                     <strong>asecret:</strong><small> {{ workspace.asecret }}</small><br>
                     <strong>csecret:</strong><small> {{ workspace.csecret }}</small><br>
                     <strong>atoken:</strong><small> {{ workspace.atoken }}</small>
                    {% else %}
		                <div class="panel-body">
		                <img src="{% static "extracao/images/face.jpg" %}" class="img-responsive">
		                    <h4>{{ workspace.extracao_facebook }}</h4>
		                    <h4><small><strong>User Token:</strong> {{ workspace.user_token }}</small></h4>
		                </div>
                	{% endif %}
            </div>
        </div>
    </div>
    <div class="row">
        {% if workspace.extracao_twitter %}
        
        <div class="col-sm-4 col-md-4">
	         <ul class="nav nav-pills" style="margin: 2px 2px;">
	            <li role="presentation" class="active"><a href="{% url 'extracao:detail_process' workspace.id %}">Vizualizar</a></li>
	            <li role="presentation"><a href="{% url 'extracao:create_twitter_post' workspace.id %}">Extrair</a></li>
	            <li role="presentation"><a href="{% url 'extracao:processing_twitter_post' workspace.id %}">Pré-Processamento</a></li>
	             <!-- Baixar -->
       			  <div class="dropup">
				    <button class="btn btn-default dropdown-toggle" type="button" id="menu1" data-toggle="dropdown">
				    <span class="glyphicon glyphicon-download-alt "></span></button>
				    <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
				      <li role="presentation"><a href="{% url 'extracao:export_process_tweet' tipo='csv' %}" class="btn btn-default btn-sm" role="button">CSV</a></li>
				      <li role="presentation"><a href="{% url 'extracao:export_process_tweet' tipo='json' %}" class="btn btn-default btn-sm" role="button">JSON</a></li>
				      <li role="presentation"><a href="{% url 'extracao:export_process_tweet' tipo='xls' %}" class="btn btn-default btn-sm" role="button">XLS</a></li>
				    </ul>
				  </div>  
	         </ul>
        </div>
        {% else %}
        <div class="col-sm-4 col-md-4">
	         <ul class="nav nav-pills" style="margin: 2px 2px;">
	            <li role="presentation" class="active"><a href="{% url 'extracao:detail_process' workspace.id %}">Vizualizar</a></li>
	            <li role="presentation"><a href="{% url 'extracao:create_facebook_post' workspace.id %}">Extrair</a></li>
	            <li role="presentation"><a href="{% url 'extracao:processing_facebook_post' workspace.id %}">Pré-Processamento</a></li>
                  <!-- Baixar -->
       			  <div class="dropup">
				    <button class="btn btn-default dropdown-toggle" type="button" id="menu1" data-toggle="dropdown">
				    <span class="glyphicon glyphicon-download-alt "></span></button>
				    <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
				      <li role="presentation"><a href="{% url 'extracao:export_process_post' tipo='csv' %}" class="btn btn-default btn-sm" role="button">CSV</a></li>
				      <li role="presentation"><a href="{% url 'extracao:export_process_post' tipo='json' %}" class="btn btn-default btn-sm" role="button">JSON</a></li>
				      <li role="presentation"><a href="{% url 'extracao:export_process_post' tipo='xls' %}" class="btn btn-default btn-sm" role="button">XLS</a></li>
				    </ul>
				  </div>  
	         </ul>
        </div>
		{% endif %}
   </div>
   <div class="row">	
        <!-- Right post Info -->
        <div class="col-sm-4 col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    
                    {% if workspace.extracao_twitter %}
                    	<table id="exemplo" class="table table-striped table-bordered" cellspacing="0" width="100%">
				          	<thead>
				          		<tr>
				              		<th>tweet_origin</th>
				              		<th>tweet_processado</th>
				          	    </tr>
				            </thead>
				            <tfoot>
				            	<tr>
				                	<th>tweet_origin</th>
				              		<th>tweet_processado</th>
				           	   </tr>
				            </tfoot>
				            
				            <tbody>
				        	{% for tweet in workspace.processamento_tweet_set.all %}
	                           <tr>                      
	                              <!-- nome coluna: tweet_origin -->
	                              <td>
	                                 {{tweet.tweet_origin}}
	                              </td>
	                              <!-- nome coluna: tweet processado -->
	                              <td>
	                                 {{tweet.tweet_process}}
	                              </td>
	                            </tr>
	                        {% endfor %}
	                       </tbody>
	                    </table>
	                {% else %}
	                
                       	<table id="exemplo" class="table table-striped table-bordered" cellspacing="0" width="100%">
                       	    <thead>
			            		<tr>
			                		<th>Post_origin</th>
				                	<th>Post Processado</th> 
			            		</tr>
			        		</thead>
			        		<tfoot>
			            		<tr>
			                		<th>Post_origin</th>
				                	<th>Post Processado</th> 
			            		</tr>
			        		</tfoot>
			        		<tbody>
			        		{% for post in workspace.processamento_post_set.all %}
	                            <tr>
	                                <td>
	                                    {{post.message_origin}}
	                                </td>
	                                <td>
	                                    {{post.message}}
	                                </td>
                           		  {% endfor %}
                           		 </tr>
                            </tbody>
                        </table>
	                {% endif %}
				</div>
            </div>
        </div>
    </div>
</div>

{% endblock %}   